/*

 SCREEN1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 50 x 50
   Tile set      : G:\dragon_savior\map\graphics.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 50
#define mapHeight 50
#define mapBank 0

extern unsigned char map[];

/* End of SCREEN1.H */
